### ISSUE TITLE
Run ProcessCcd: 'CalibrateConfig' object has no attribute 'photoCal'

### ISSUE THREAD

**Issue by rbliu** [LSSTDESC/ReprocessingTaskForce#12]
Hi, this might be a trivial issue...

When I followed the Wiki page and run processCcd, it gave the following error:

> processCcd.py input --output output --id visit=806305 ccd=12 --configfile processConfig.py
> : Loading config overrride file : Loading config overrride file '/home/rliu/miniconda2/opt/lsst/my_packages/obs_cfht/config/processCcd.py'
> Traceback (most recent call last):
>   File "/home/rliu/miniconda2/opt/lsst/pipe_tasks/bin/processCcd.py", line 25, in <module>
>     ProcessCcdTask.parseAndRun()
>   File "/home/rliu/miniconda2/opt/lsst/pipe_base/python/lsst/pipe/base/cmdLineTask.py", line 433, in parseAndRun
>     parsedCmd = argumentParser.parse_args(config=config, args=args, log=log, override=cls.applyOverrides)
>   File "/home/rliu/miniconda2/opt/lsst/pipe_base/python/lsst/pipe/base/argumentParser.py", line 360, in parse_args
>     self._applyInitialOverrides(namespace)
>   File "/home/rliu/miniconda2/opt/lsst/pipe_base/python/lsst/pipe/base/argumentParser.py", line 475, in _applyInitialOverrides
>     namespace.config.load(filePath)
>   File "/home/rliu/miniconda2/opt/lsst/pex_config/python/lsst/pex/config/config.py", line 529, in load
>     self.loadFromStream(stream=code, root=root)
>   File "/home/rliu/miniconda2/opt/lsst/pex_config/python/lsst/pex/config/config.py", line 549, in loadFromStream
>     exec stream in {}, local
>   File "/home/rliu/miniconda2/opt/lsst/my_packages/obs_cfht/config/processCcd.py", line 6, in <module>
>     config.calibrate.photoCal.colorterms.load(os.path.join(cfhtConfigDir, 'colorterms.py'))
>   File "/home/rliu/miniconda2/opt/lsst/pex_config/python/lsst/pex/config/configurableField.py", line 103, in __getattr__
>     return getattr(self._value, name)
> **AttributeError: 'CalibrateConfig' object has no attribute 'photoCal'**
> ###### 
> 
> For clarification, I have setup pipe_tasks, obs_cfht, tmv, galsim, meas_extensions_shapeHSM, and astrometry_net_data (with dr9 healpix #176 and 503). Also I think the input directory has been generated as in the instruction.

I also tried to move the row "config.calibrate.photoCal.applyColorTerms = True" to the beginning of ~/obs_cfht/config/processCcd.py, but the same error came out. So I was wondering if there were any config parameters that I missed?

**Comment by boutigny** [comment]
Hi Robert,

I think that this is due to the recent change in the processCcd task 
which has been re-factored. I need to update the documentation on the 
Wiki page but haven't had a chance to do it yet.

Could you please try with the following configuration file which 
contains updated parameter names ?

Thanks for trying to use these instructions and sorry for the outdated 
documentation (I promise  that I will update it asap).

Dominique

config.isr.doBrighterFatter=False

config.charImage.repair.cosmicray.nCrPixelMax=1000000

from lsst.meas.astrom.anetAstrometry import ANetAstrometryTask
config.calibrate.astrometry.retarget(ANetAstrometryTask)
config.calibrate.astrometry.solver.sipOrder=3

#config.charImage.astrometry.wcsFitter.order=3
#onfig.charImage.astrometry.matcher.maxMatchDistArcSec=3.0

#config.calibrate.astrometry.refObjLoader.filterMap = { 'i2': 'i',

# }

config.charImage.astrometry.refObjLoader.filterMap = { 'i2': 'i'}

config.calibrate.photoCal.fluxField='base_CircularApertureFlux_6_0_flux'
config.calibrate.photoCal.magLimit=22.0
config.calibrate.photoCal.photoCatName="e2v"
config.calibrate.photoCal.applyColorTerms=True
config.calibrate.photoCal.badFlags=['base_PixelFlags_flag_edge', 
'base_PixelFlags_flag_interpolated', 'base_PixelFlags_flag_saturated', 
'base_PixelFlags_flag_crCenter']

import lsst.pipe.tasks.colorterms
config.calibrate.photoCal.colorterms.data['e2v'].data['i2']=lsst.pipe.tasks.colorterms.Colorterm()
config.calibrate.photoCal.colorterms.data['e2v'].data['i2'].c2=0.0
config.calibrate.photoCal.colorterms.data['e2v'].data['i2'].c1=0.085
config.calibrate.photoCal.colorterms.data['e2v'].data['i2'].c0=0.0
config.calibrate.photoCal.colorterms.data['e2v'].data['i2'].primary='i'
config.calibrate.photoCal.colorterms.data['e2v'].data['i2'].secondary='r'

# use Chebyshev background estimation

config.charImage.background.useApprox=True
config.charImage.detectAndMeasure.detection.background.binSize=128
config.charImage.detectAndMeasure.detection.background.useApprox=True
config.charImage.background.binSize = 128
config.charImage.background.undersampleStyle = 'REDUCE_INTERP_ORDER'
config.charImage.detectAndMeasure.detection.background.binSize = 128
config.charImage.detectAndMeasure.detection.background.undersampleStyle='REDUCE_INTERP_ORDER'
config.charImage.detectAndMeasure.detection.background.binSize = 128
config.charImage.detectAndMeasure.detection.background.undersampleStyle 
= 'REDUCE_INTERP_ORDER'

On 31/03/2016 22:10, Robert wrote:

> Hi, this might be a trivial issue...
> 
> When I followed the Wiki page and run processCcd, it gave the 
> following error:
> 
> ```
> processCcd.py input --output output --id visit=806305 ccd=12
> --configfile processConfig.py
> : Loading config overrride file : Loading config overrride file
> '/home/rliu/miniconda2/opt/lsst/my_packages/obs_cfht/config/processCcd.py'
> Traceback (most recent call last):
> File
> "/home/rliu/miniconda2/opt/lsst/pipe_tasks/bin/processCcd.py",
> line 25, in
> ProcessCcdTask.parseAndRun()
> File
> "/home/rliu/miniconda2/opt/lsst/pipe_base/python/lsst/pipe/base/cmdLineTask.py",
> line 433, in parseAndRun
> parsedCmd = argumentParser.parse_args(config=config, args=args,
> log=log, override=cls.applyOverrides)
> File
> "/home/rliu/miniconda2/opt/lsst/pipe_base/python/lsst/pipe/base/argumentParser.py",
> line 360, in parse_args
> self./applyInitialOverrides(namespace)
> File
> "/home/rliu/miniconda2/opt/lsst/pipe_base/python/lsst/pipe/base/argumentParser.py",
> line 475, in /applyInitialOverrides
> namespace.config.load(filePath)
> File
> "/home/rliu/miniconda2/opt/lsst/pex_config/python/lsst/pex/config/config.py",
> line 529, in load
> self.loadFromStream(stream=code, root=root)
> File
> "/home/rliu/miniconda2/opt/lsst/pex_config/python/lsst/pex/config/config.py",
> line 549, in loadFromStream
> exec stream in {}, local
> File
> "/home/rliu/miniconda2/opt/lsst/my_packages/obs_cfht/config/processCcd.py",
> line 6, in
> config.calibrate.photoCal.colorterms.load(os.path.join(cfhtConfigDir,
> 'colorterms.py'))
> File
> "/home/rliu/miniconda2/opt/lsst/pex_config/python/lsst/pex/config/configurableField.py",
> line 103, in __getattr//
> return getattr(self._value, name)
> *AttributeError: 'CalibrateConfig' object has no attribute 'photoCal'*
> ####################################################
> For clarification, I have setup pipe_tasks, obs_cfht, tmv, galsim,
> meas_extensions_shapeHSM, and astrometry_net_data (with dr9
> healpix #176 and 503). Also I think the input directory has been
> generated as in the instruction.
> ```
> 
> I also tried to move the row 
> "config.calibrate.photoCal.applyColorTerms = True" to the beginning of 
> ~/obs_cfht/config/processCcd.py, but the same error came out. So I was 
> wondering if there were any config parameters that I missed?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/DarkEnergyScienceCollaboration/ReprocessingTaskForce/issues/12

## 

Dominique Boutigny

Laboratoire d'Annecy-le-Vieux de Physique des Particules
Université Savoie Mont Blanc - CNRS/IN2P3
Tel : 04.50.09.16.80 - 07.83.59.06.65
Bureau: 4-110

**Comment by boutigny** [comment]
I have updated the Wiki page. Please tell me if you run into other problems.
